language: node_js
node_js:
  - 6
  - 8
  - 10
before_install:
  - stty columns 120
install:
  - npm install --ignore-scripts
script:
  - npm test
  - npm run example:default
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
